package com.softdesign.devintensive.utils;

public interface ConstantManager {
    String TAG_PREFIX="DEV ";
    String EDIT_MORE_KEY = "EDIT_MORE_KEY ";

    String USER_PHONE_KEY="USER_1_KEY";
    String USER_MAIL_KEY="USER_2_KEY";
    String USER_VK_KEY="USER_3_KEY";
    String USER_GIT_KEY="USER_4_KEY";
    String USER_BIO_KEY="USER_5_KEY";

    String USER_PHOTO_KEY="USER_PHOTO_KEY";
    String USER_AVATAR_VALUE ="USER_AVATAR_VALUE" ;
    String USER_RATING_VALUE="USER_RATING_VALUE";
    String USER_CODE_LINES_VALUE="USER_CODE_LINES_VALUE";
    String USER_PROJECT_VALUE="USER_PROJECT_VALUE";
    String USER_FIRSTNAME_KEY="USER_FIRSTNAME_KEY";
    String USER_SECONDNAME_KEY="USER_SECONDNAME_KEY";
    String USER_MAIL_KEY1 ="USER_MAIL_KEY1" ;
    String AUTH_TOKEN_KEY ="AUTH_TOKEN_KEY" ;
    String USER_ID_KEY ="USER_ID_KEY" ;


    int LOAD_PROFILE_MANAGER=1;
    int LOAD_PROFILE_PHOTO=1;
    int REQUEST_CAMERA_PICTURE=99;
    int REQUEST_GALLERY_PICTURE=88;


    int PERMISSION_REQUEST_SETTINGS_CODE=101;
    int CAMERA_REQUEST_PERMISSION_CODE=102;



}
